# `try` `catch`
An **exception** provide an ***alternative flow*** to deal with ***runtime errors***. When a runtime error occur, Java ***create*** and ***throw*** an `Exception` class. We need to protect the code that can `throw` an exception by expressing ***what needs to happen***
```
try {
	// Risky code
} catch (Exception e) {
	// handle exception
} finally { 
	// Wrap up / clean up
}
```

## Exemple:
```
public int intDivide(int i, int j) {
	try {
		return i / j;
	} catch (Exception e) {
		return 0;
	}	
}
```
> `finally` is optional

## Nested Try-Catch
```
try {
	try {
		// other risky code
	} catch (Exception e) {
		// handle exception for the inner try
	}
	catch (Exception e) {
	...
```

# `throw`
```
throw new ArithmeticExeption("You passed zero for the denominator!");
```

# Exception Types
`Exception` and `Error` inherits from `Throwable` class
> `Error` are critical system errors we are not in control.