### Callbacks

A callback is a function passed to another function, for it to call.
It is used to be executed when asynchronous operation is completed.

Callbacks are used with:

- Functional programming
- Event-driven programming

> Alternativly, we can use asyn/await instead of callbacks

##### Callback Hell

Before Promises, the only way to deal with multiple asyncrhonise function was by nested callbacks

```javascript
var response = ajaxLibrary.get("/page1", function (response) {
  ajaxLibrary.get("/page2", function (response2) {
    // ...
  });
});
```

> The only solution to this callback hell is to use **Promises**

### Promises

- A Promise is an object that represents the eventual completion or failure of an asynchronous operation and its resulting value.
- It can be in one of those 3 states: **_Pending, Resolved, Rejected_**

```javascript
const myPromise = new Promise((resolve, reject) => {});
```

> Note: **we can not directly query the current state of a Promises**, we can only check the state indirectly by using the `.then()`, `.catch()`, or `.finally()` methods

### Using `then()` and `catch()`

- Promises provide a `then()` and `catch()` methods which both accept callbacks.
- The `then()` callback will run if the Promise is resolved
- The `catch()` callback will run if the Promise is rejected

```javascript
fetch(url)
  .then((res) => console.log(res))
  .catch((err) => console.log("ERR!", err));
```

> We are still using callback with `then/catch` that can lead to callback hell with nested `then()`

##### Promise Chaining

We can return a Promise in the then() callback, so we can chain another `then()`, and to avoid callback hell, and call `catch()` at the end

We can avoid the callback hell by returning a Promise in the `then()` callback to chain another `then()`

```javascript
fetch(url1)
  .then(fetch(url2))
  .then(fetch(url3))
  .catch((err) => console.log(err));
```

> We need to return a Promise to be able to chain `then()`

### The `async/await` Keyword

We can use `async/await` instead of `then/catch`

- `async` functions **always** return promises
- `await` pauses execution waiting for the Promise to be resolve

```javascript
async function hello() {}
hello(); // Promise {...}
```

```javascript
async function getAPI() {
  const result = await fetch(url);
  console.log(result);
}
```

Instead of chaining like with then() we write await statement in sequence:

```javascript
async function getAPI() {
  const res1 = await fetch(url1);
  const res2 = await fetch(url2);
  // ...
}
```

##### Error Handling With `async`

We use standard `try/catch` to handle errors with `async` function

```javascript
async function getAPI() {
  try {
    const result = await fetch("http:/none.any");
  } catch (e) {
    console.log(e);
  }
}

getAPI(); // 404 (Not Found)
```

> Note: `catch` will catch any error inside the `try` block, not only Promise

### `then` Vs `async`

We can run `then` in parallel, unlike `await` been sequencial

```javascript
fetch(url1).then((res) => console.log(res));
fetch(url2).then((res) => console.log(res));
fetch(url3).then((res) => console.log(res));
```

### Usefull Promise Methods

- `Promise.all()` takes an array of promises, and return an array of response

  ```javascript
  const fetchs = [url1, url2, url3];
  Promise.all(fetchs.then((res) => console.log(res)));
  ```

  > `Promise.all()` is resolved when all the Promises are resolve

  > Alternativly we could use a `async/await` sequencialy

- `Promise.allSettled()` takes an array of promises, and will resolve when all the promises are completed and returns an array of object with the results

  ```javascript
  const fetchAll = async function () {
    const results = await Promise.allSettled([
      fetch(url1), // 0: {status: 'fulfilled', value: Response}
      fetch(url2), // 1: {status: 'rejected', reason: TypeError: ...
      fetch(url3), // 2: {status: 'fulfilled', value: Response}
    ]);
    console.log(results);
  };

  fetchAll(); // [{…}, {…}, {…}]
  ```

  We can then `filter()` the result

  ```javascript
  let fulfilled = fetchAll.filter((r) => r.status === "fulfilled");
  ```

- `Promise.any()` takes an array of promises, and will resolve if one of the promises is resolved, all of them needs to be rejected to return rejected
- `Promise.race()` takes an array of promises, and will resolve as soon the first promise is resolved

### Building Our Own Promise

- We make our own Promise with the `new` keyword
- Promise accepts a single function (call it `fn`) as an argument
- `fn` accepts 2 functions as arguments, (call them) `resolve` and `reject`

The Promise will be return as soon `resolve(response)` or `reject(error)` is called

```javascript
function wait() {
  return new Promise(function (resolve, reject) {
    setTimeout(() => resolve("returned value!"), 1000);
  });
}

async function demo() {
  const val = await wait();
  console.log(val); // returned value!
}
```

> The `reject()` returned will be accessible with the `catch(e)`
